"""Debug and export-oriented services."""

import os
import tempfile

import renderdoc as rd


class ExportServiceMixin:
    @staticmethod
    def _overlay_enum(name):
        overlay_map = {
            "drawcall": rd.DebugOverlay.Drawcall,
            "highlight_drawcall": rd.DebugOverlay.Drawcall,
            "wireframe": rd.DebugOverlay.Wireframe,
            "depth": rd.DebugOverlay.Depth,
            "stencil": rd.DebugOverlay.Stencil,
            "backface_cull": rd.DebugOverlay.BackfaceCull,
            "viewport_scissor": rd.DebugOverlay.ViewportScissor,
            "clear_before_draw": rd.DebugOverlay.ClearBeforeDraw,
            "clear_before_pass": rd.DebugOverlay.ClearBeforePass,
            "triangle_size_draw": rd.DebugOverlay.TriangleSizeDraw,
            "triangle_size_pass": rd.DebugOverlay.TriangleSizePass,
            "quad_overdraw_draw": rd.DebugOverlay.QuadOverdrawDraw,
            "quad_overdraw_pass": rd.DebugOverlay.QuadOverdrawPass,
        }
        return overlay_map.get(str(name or "").lower())

    def debug_resource_ctx(self, params):
        rid = params.get("rid")
        eid = params.get("eid")
        if rid is None or eid is None:
            return {
                "ok": False,
                "mode": "summary",
                "data": None,
                "err": {"code": "missing_args", "msg": "rid and eid are required"},
                "meta": {"cap": "active", "truncated": False},
            }

        ctx = self._binding_context_for_event(rid, int(eid))
        return {
            "ok": True,
            "mode": "summary",
            "data": {
                "rid": str(rid),
                "eid": int(eid),
                "ctx": ctx,
            },
            "err": None,
            "meta": {"cap": "active", "truncated": False},
        }

    def debug_resource_info(self, params):
        rid = params.get("rid")
        if rid is None:
            return {
                "ok": False,
                "mode": "summary",
                "data": None,
                "err": {"code": "missing_args", "msg": "rid is required"},
                "meta": {"cap": "active", "truncated": False},
            }

        target = None
        resources = self.ctx.GetResources()
        for res in resources:
            if str(res.resourceId) == str(rid):
                target = res
                break

        if target is None:
            return {
                "ok": False,
                "mode": "summary",
                "data": None,
                "err": {"code": "not_found", "msg": "resource not found"},
                "meta": {"cap": "active", "truncated": False},
            }

        return {
            "ok": True,
            "mode": "summary",
            "data": {
                "rid": str(target.resourceId),
                "name": target.name,
                "type": str(target.type).split(".")[-1],
                "autogen": bool(target.autogeneratedName),
                "parents": [str(x) for x in target.parentResources],
                "derived": [str(x) for x in target.derivedResources],
            },
            "err": None,
            "meta": {"cap": "active", "truncated": False},
        }

    def debug_save_texture(self, params):
        rid = params.get("rid")
        eid = params.get("eid")
        dest_value = params.get("dest")
        dest_format = params.get("format") or params.get("type")
        dest_path = params.get("path") or params.get("output")
        if dest_value is not None:
            dest_text = str(dest_value)
            if dest_text.upper() in ("PNG", "HDR", "DDS") and dest_format is None and dest_path is None:
                dest_format = dest_text
            elif dest_path is None:
                dest_path = dest_text
        if dest_format is None and dest_path is not None:
            suffix = os.path.splitext(str(dest_path))[1].lower().lstrip(".")
            if suffix in ("png", "hdr", "dds"):
                dest_format = suffix
        dest = str(dest_format or "PNG").upper()
        if rid is None:
            return {
                "ok": False,
                "mode": "summary",
                "data": None,
                "err": {"code": "missing_args", "msg": "rid is required"},
                "meta": {"cap": "active", "truncated": False},
            }

        result = {"path": None, "error": None, "format": dest, "requested_dest": dest_path}

        def collect(controller):
            if eid is not None:
                controller.SetFrameEvent(int(eid), True)

            save = rd.TextureSave()
            resolved = None
            for tex in controller.GetTextures():
                if str(tex.resourceId) == str(rid):
                    resolved = tex.resourceId
                    break
            if resolved is None:
                result["error"] = "Texture resource not found in current capture"
                return
            save.resourceId = resolved
            ext = "png"
            if dest == "HDR":
                save.destType = rd.FileType.HDR
                ext = "hdr"
            elif dest == "DDS":
                save.destType = rd.FileType.DDS
                ext = "dds"
                save.mip = -1
                save.slice.sliceIndex = -1
            else:
                save.destType = rd.FileType.PNG
            save.alpha = rd.AlphaMapping.Preserve
            if dest != "DDS":
                save.mip = 0
                save.slice.sliceIndex = 0
            try:
                out_path = self._resolve_export_path(dest_path, "texture", rid, eid, ext, bool(params.get("overwrite")))
            except Exception as exc:
                result["error"] = str(exc)
                return
            try:
                res = controller.SaveTexture(save, out_path)
                result["path"] = out_path if os.path.exists(out_path) else None
                result["error"] = None if result["path"] else str(res)
            except Exception as exc:
                result["error"] = str(exc)

        self.ctx.Replay().BlockInvoke(collect)

        return {
            "ok": result["path"] is not None,
            "mode": "summary",
            "data": result,
            "err": None if result["path"] else {"code": "save_failed", "msg": result["error"]},
            "meta": {"cap": "active", "truncated": False},
        }

    def debug_save_overlay(self, params):
        eid = params.get("eid")
        overlay_name = params.get("overlay", "drawcall")
        rid = params.get("rid")
        dest = str(params.get("dest", "PNG")).upper()

        if eid is None:
            return {
                "ok": False,
                "mode": "summary",
                "data": None,
                "err": {"code": "missing_args", "msg": "eid is required"},
                "meta": {"cap": "active", "truncated": False},
            }

        overlay_enum = self._overlay_enum(overlay_name)
        if overlay_enum is None:
            return {
                "ok": False,
                "mode": "summary",
                "data": None,
                "err": {"code": "bad_overlay", "msg": "unsupported overlay: {}".format(overlay_name)},
                "meta": {"cap": "active", "truncated": False},
            }

        out_dir = os.path.join(tempfile.gettempdir(), "renderdoc_mcp_exports")
        os.makedirs(out_dir, exist_ok=True)
        result = {"path": None, "error": None, "target_rid": None, "overlay_rid": None}

        def collect(controller):
            controller.SetFrameEvent(int(eid), True)
            pipe = controller.GetPipelineState()

            target_rid = None
            if rid is not None:
                target_rid = str(rid)
            else:
                try:
                    for out in pipe.GetOutputTargets():
                        res = getattr(out, "resource", None)
                        res_str = str(res)
                        if res_str and "Null" not in res_str and res_str != "ResourceId::0":
                            target_rid = res_str
                            break
                except Exception as exc:
                    self._warn_swallow("export.debug_save_overlay.output_targets", exc)
                    target_rid = None

            if target_rid is None:
                result["error"] = "No output render target found for overlay export"
                return

            tex_details = None
            resolved = None
            for tex in controller.GetTextures():
                if str(tex.resourceId) == target_rid:
                    tex_details = tex
                    resolved = tex.resourceId
                    break

            if resolved is None:
                result["error"] = "Target texture resource not found in current capture"
                return

            width = int(getattr(tex_details, "width", 256) or 256)
            height = int(getattr(tex_details, "height", 256) or 256)
            result["target_rid"] = target_rid

            out = None
            try:
                out = controller.CreateOutput(
                    rd.CreateHeadlessWindowingData(width, height),
                    rd.ReplayOutputType.Texture,
                )
                tex_display = rd.TextureDisplay()
                tex_display.resourceId = resolved
                tex_display.overlay = overlay_enum
                tex_display.subresource.mip = 0
                tex_display.subresource.slice = 0
                tex_display.subresource.sample = 0
                out.SetTextureDisplay(tex_display)
                out.Display()
                overlay_rid = out.GetDebugOverlayTexID()
                overlay_rid_str = str(overlay_rid)
                result["overlay_rid"] = overlay_rid_str

                if not overlay_rid_str or "Null" in overlay_rid_str or overlay_rid_str == "ResourceId::0":
                    result["error"] = "Overlay texture was not generated"
                    return

                save = rd.TextureSave()
                save.resourceId = overlay_rid
                ext = "png"
                if dest == "HDR":
                    save.destType = rd.FileType.HDR
                    ext = "hdr"
                elif dest == "DDS":
                    save.destType = rd.FileType.DDS
                    ext = "dds"
                    save.mip = -1
                    save.slice.sliceIndex = -1
                else:
                    save.destType = rd.FileType.PNG
                save.alpha = rd.AlphaMapping.Preserve
                if dest != "DDS":
                    save.mip = 0
                    save.slice.sliceIndex = 0

                out_path = os.path.join(
                    out_dir,
                    "overlay_{}_{}_{}.{}".format(
                        str(overlay_name).lower(),
                        str(eid),
                        target_rid.replace("::", "_"),
                        ext,
                    ),
                )
                save_res = controller.SaveTexture(save, out_path)
                result["path"] = out_path if os.path.exists(out_path) else None
                result["error"] = None if result["path"] else str(save_res)
            except Exception as exc:
                result["error"] = str(exc)
            finally:
                if out is not None:
                    try:
                        controller.ShutdownOutput(out)
                    except Exception as exc:
                        self._warn_swallow("export.debug_save_overlay.shutdown_output", exc)

        self.ctx.Replay().BlockInvoke(collect)

        return {
            "ok": result["path"] is not None,
            "mode": "summary",
            "data": result,
            "err": None if result["path"] else {"code": "save_failed", "msg": result["error"]},
            "meta": {"cap": "active", "truncated": False},
        }

    @staticmethod
    def _resolve_export_path(dest_path, prefix, rid, eid, ext, overwrite):
        safe_rid = str(rid).replace("::", "_").replace(":", "_").replace("\\", "_").replace("/", "_")
        eid_part = "_eid{}".format(eid) if eid is not None else ""
        filename = "{}_{}{}.{}".format(prefix, safe_rid, eid_part, ext)

        if dest_path:
            path = os.path.abspath(str(dest_path))
            root, suffix = os.path.splitext(path)
            is_dir = (
                os.path.isdir(path)
                or str(dest_path).endswith(("\\", "/"))
                or suffix.lower() not in (".png", ".hdr", ".dds")
            )
            out_path = os.path.join(path, filename) if is_dir else path
        else:
            out_dir = os.path.join(tempfile.gettempdir(), "renderdoc_mcp_exports")
            out_path = os.path.join(out_dir, filename)

        out_dir = os.path.dirname(out_path)
        os.makedirs(out_dir, exist_ok=True)

        if overwrite or not os.path.exists(out_path):
            return out_path

        root, suffix = os.path.splitext(out_path)
        for idx in range(1, 10000):
            candidate = "{}_{:03d}{}".format(root, idx, suffix)
            if not os.path.exists(candidate):
                return candidate
        raise RuntimeError("Could not find a non-conflicting export path for {}".format(out_path))
